version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_LANGUAGE_SHEET_API_KEY=AIzaSyDpmhMGIfXJGXJ6rszaBGW3LuqVo49t_bA
      - NEXT_PUBLIC_LANGUAGE_SPREAD_SHEET_ID=11AkdGEAf8dOrRV4A6uP_4HRCYhfQkt3FEIAQv86pqNo
      - NEXT_PUBLIC_LANGUAGE_SHEET_RANGE=Sheet1!A:ZZ
      - NEXT_PUBLIC_BASE_URL=https://ats-be.vedastudios.com.np/api/v1
      - NEXT_PUBLIC_IMAGE_URL=https://d3o9ect5czyljq.cloudfront.net
    restart: unless-stopped

  

  # candidate:
  #   build:
  #     context: .
  #     dockerfile: apps/candidate/Dockerfile
  #   ports:
  #     - '3002:3000'
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped

  # super-admin:
  #   build:
  #     context: .
  #     dockerfile: apps/super-admin/Dockerfile
  #   ports:
  #     - '3003:3000'
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
